export const categories = [
	{ value: "Algorithms", label: "Algorithms" },
	{ value: "Data Structures", label: "Data Structures" },
	{ value: "JavaScript", label: "JavaScript" },
	{ value: "Python", label: "Python" },
	{ value: "Java", label: "Java" },
	{ value: "C++", label: "C++" },
	{ value: "C#", label: "C#" },
	{ value: "Ruby", label: "Ruby" },
	{ value: "Swift", label: "Swift" },
	{ value: "Kotlin", label: "Kotlin" },
	{ value: "TypeScript", label: "TypeScript" },
	{ value: "Go", label: "Go" },
	{ value: "Rust", label: "Rust" },
	{ value: "Shell Scripting", label: "Shell Scripting" },
	{ value: "Web Development", label: "Web Development" },
	{ value: "Mobile Development", label: "Mobile Development" },
	{ value: "Game Development", label: "Game Development" },
	{ value: "Database", label: "Database" },
	{ value: "Machine Learning", label: "Machine Learning" },
	{ value: "Artificial Intelligence", label: "Artificial Intelligence" },
	{ value: "Cloud Computing", label: "Cloud Computing" },
	{ value: "DevOps", label: "DevOps" },
	{ value: "Software Testing", label: "Software Testing" },
	{ value: "Software Architecture", label: "Software Architecture" },
	{ value: "Cybersecurity", label: "Cybersecurity" },
	{ value: "Data Science", label: "Data Science" },
	{ value: "Functional Programming", label: "Functional Programming" },
	{
		value: "Object-Oriented Programming",
		label: "Object-Oriented Programming",
	},
	{ value: "Frontend Development", label: "Frontend Development" },
	{ value: "Backend Development", label: "Backend Development" },
	{ value: "Full Stack Development", label: "Full Stack Development" },
	{ value: "Microservices", label: "Microservices" },
	{ value: "GraphQL", label: "GraphQL" },
	{ value: "Docker", label: "Docker" },
	{ value: "Kubernetes", label: "Kubernetes" },
	{ value: "Serverless", label: "Serverless" },
	{ value: "APIs", label: "APIs" },
	{ value: "Blockchain", label: "Blockchain" },
	{ value: "IoT", label: "Internet of Things" },
	{ value: "Augmented Reality", label: "Augmented Reality" },
	{ value: "Virtual Reality", label: "Virtual Reality" },
	{ value: "Data Visualization", label: "Data Visualization" },
	{ value: "UX/UI Design", label: "UX/UI Design" },
	{ value: "Open Source", label: "Open Source" },
	{ value: "Performance Optimization", label: "Performance Optimization" },
	{ value: "Scalability", label: "Scalability" },
	{
		value: "Software Engineering Principles",
		label: "Software Engineering Principles",
	},
	{ value: "Coding Best Practices", label: "Coding Best Practices" },
	{ value: "Project Management", label: "Project Management" },
	{ value: "Agile Development", label: "Agile Development" },
	{ value: "Scrum", label: "Scrum" },
	{ value: "Other", label: "Other" },
];
